apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: tweet-service
  name: tweet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tweet-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: tweet-service
    spec:
      containers:
        - image: daniil2231/twitterv2:tweet
          name: tweet-service
          ports:
            - containerPort: 8082
          resources: {}
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
status: {}
